name: Build and release EXE

on:
  push:
    tags: ['v*.*.*']

permissions:
  contents: write   # нужно, чтобы заливать файлы в Releases

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (no lock)
        shell: pwsh
        run: |
          if (Test-Path package-lock.json) { Remove-Item package-lock.json -Force }
          npm install

      - name: Build frontend (Vite)
        run: npm run build

      - name: Build Windows installer (no publish)
        run: npx electron-builder --win nsis -p never

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: win-installer
          path: |
            dist/**/*.exe

      - name: Attach .exe to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
